// <auto-generated />
using ApiTuristas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiTuristas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiAtractivo.Models.AtractivoTuristico", b =>
                {
                    b.Property<int>("AtractivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AtractivoId"));

                    b.Property<string>("Actividades")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Horario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagenPrincipal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrecioEntrada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AtractivoId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Atractivos");
                });

            modelBuilder.Entity("ApiCategoria.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("ApiImagen.Models.ImagenAtractivo", b =>
                {
                    b.Property<int>("ImagenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImagenId"));

                    b.Property<int>("AtractivoId")
                        .HasColumnType("integer");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ImagenId");

                    b.HasIndex("AtractivoId");

                    b.ToTable("Imagenes");
                });

            modelBuilder.Entity("ApiTuristas.Models.Turista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("turistas");
                });

            modelBuilder.Entity("ApiAtractivo.Models.AtractivoTuristico", b =>
                {
                    b.HasOne("ApiCategoria.Models.Categoria", "Categoria")
                        .WithMany("Atractivos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ApiImagen.Models.ImagenAtractivo", b =>
                {
                    b.HasOne("ApiAtractivo.Models.AtractivoTuristico", "Atractivo")
                        .WithMany("Imagenes")
                        .HasForeignKey("AtractivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atractivo");
                });

            modelBuilder.Entity("ApiAtractivo.Models.AtractivoTuristico", b =>
                {
                    b.Navigation("Imagenes");
                });

            modelBuilder.Entity("ApiCategoria.Models.Categoria", b =>
                {
                    b.Navigation("Atractivos");
                });
#pragma warning restore 612, 618
        }
    }
}
